runtime: php56
api_version: 1
threadsafe: yes

handlers:

# react profile page
- url: /app
  static_dir: public/app
- url: /models
  static_dir: public/models

- url: /css
  static_dir: public/css

# JavaScript
- url: /js/pay_with_stripe.js
  script: pay_with_stripe.php
- url: /js/JSXTransformer.js
  script: js/JSXTransformer.js
- url: /js
  static_dir: public/js

- url: /images
  static_dir: public/images
- url: /images/team
  static_dir: public/images/team

- url: /fonts
  static_dir: public/fonts

- url: /assets
  static_dir: public/assets

- url: /templates
  static_dir: public/templates
  application_readable: true

# Google Polymer Components
- url: /components/
  static_dir: components/
#- url: /elements/
#  static_dir: elements/

# catchall for php routing
- url: /.*
  script: public/index.php
