application: stone-timing-557
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /images
  static_dir: images
- url: /models
  static_dir: models
- url: /
  script: index.html
- url: /(.+\)$
  script: \1

